// import { Geist, Geist_Mono } from "next/font/google";
import { cn } from "@/lib/utils";
import "../styles/globals.scss";
import Header from "@/components/organisms/header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, container }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className={cn(!container ? "container" :"")}>
          {children}
        </main>
      </body>
    </html>
  );
}
